# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [48]:
a = np.random.randint(0, 10, size = (8, 10))
b = a.sum(axis=1)
minim = np.amin(b)
for i in range(len(b)):
    if b[i] != minim:
        continue
    else:
        break
a[i]

array([0, 3, 3, 1, 6, 0, 5, 2, 2, 9])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [13]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype='int32')
print(data[:5])    

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [111]:
print(np.mean(data[:, 1:], axis=0))
print(np.argmin(data[:, 1:], axis=0))
print(np.argmax(data[:, 1:], axis=0))
print(np.median(data[:, 1:], axis=0))

[2.16010017e+04 9.05528000e+00]
[  411 13006]
[15653 36140]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [112]:
data[:, 1] = np.clip(data[:, 1], 0, np.quantile(data[:, 1], 0.75))
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [116]:
print(len(data[data[:, 1] == 0]))
data[data[:, 1] == 0] = 1
data[data[:, 1] == 1]

0


array([[352940,      1,      3],
       [ 47249,      1,      8],
       [     1,      1,      1],
       ...,
       [155921,      1,      2],
       [     1,      1,      1],
       [     1,      1,      1]], dtype=int32)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [87]:
len(np.unique(data[:, :1]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [117]:
print(len(set(data[:, 2])))

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [120]:
a = data[data[:, 2] <= 5].copy()
a

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [124]:
np.array([data[:, 2] / data[:, 1]]).max(axis=0)

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.21538462])

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [4]:
result = data[data[:, 1].argsort()[::-1]][:100]
np.mean(result[:, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [5]:
result = np.random.randint(0, 100000, size=(1, 10))
print(data[result])

[[[257777    100      8]
  [ 81007     65     11]
  [  5186     55     12]
  [ 44415    155      9]
  [278758    100     10]
  [ 34726    190      5]
  [197381     25     10]
  [214121     35     14]
  [263858      8      8]
  [ 98149     45      4]]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [6]:
result = data[:, 2] <= np.mean(data[:, 2])
len(data[result, :]) / len(data) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [7]:
data2 = data.copy()
simple = [1 if (row[1] <= 20) & (row[2] <= 5) else 0 for row in data2]
res = np.insert(data2, 3, simple, axis=1)
res

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [8]:
len(res[(res[:, 3] == 1)]) / len(data) * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.